# Dockerfile.dev

# 베이스 이미지 선택
FROM openjdk:21-jdk-slim

# 작업 디렉토리 설정
WORKDIR /app

# 실행에 필요한 build 결과물을 컨테이너 안으로 복사
# build/libs 폴더의 모든 내용을 /app 폴더로 복사합니다.
COPY build/libs/*.jar app.jar

# 컨테이너가 시작될 때 실행할 명령어
# fat JAR를 실행하되, devtools가 활성화되도록 실행합니다.
ENTRYPOINT ["java", "-Dspring.devtools.livereload.enabled=true", "-Dspring.devtools.restart.enabled=true", "-jar", "app.jar"]