CREATE TABLE chat_room_members (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    room_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_read_at TIMESTAMP,
    CONSTRAINT PK_CHAT_ROOM_MEMBERS PRIMARY KEY (id)
);
CREATE TABLE diary_likes (
    dlid NUMBER GENERATED ALWAYS AS IDENTITY,
    mid NUMBER NOT NULL,
    did NUMBER NOT NULL,
    CONSTRAINT PK_DIARY_LIKES PRIMARY KEY (dlid)
);
CREATE TABLE members (
    mid NUMBER GENERATED ALWAYS AS IDENTITY,
    account VARCHAR2(20 CHAR) NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL,
    pwd VARCHAR2(255 BYTE) NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    updated_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT PK_MEMBERS PRIMARY KEY (mid)
);
CREATE TABLE attachments (
    aid NUMBER GENERATED ALWAYS AS IDENTITY,
    did NUMBER NOT NULL,
    aname VARCHAR2(255 BYTE) NOT NULL,
    adata BLOB NOT NULL,
    atype VARCHAR2(50 BYTE) NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    updated_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT PK_ATTACHMENTS PRIMARY KEY (aid)
);
CREATE TABLE guestboards (
    gbid NUMBER GENERATED ALWAYS AS IDENTITY,
    hostid NUMBER NOT NULL,
    gid NUMBER NOT NULL,
    content VARCHAR2(200 CHAR) NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    updated_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT PK_GUESTBOARDS PRIMARY KEY (gbid)
);
CREATE TABLE diary_comments (
    dcid NUMBER GENERATED ALWAYS AS IDENTITY,
    did NUMBER NOT NULL,
    mid NUMBER NOT NULL,
    content VARCHAR2(1000 CHAR) NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    updated_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT PK_DIARY_COMMENTS PRIMARY KEY (dcid)
);
CREATE TABLE jukebox_likes (
    jlid NUMBER GENERATED ALWAYS AS IDENTITY,
    mid NUMBER NOT NULL,
    jid NUMBER NOT NULL,
    CONSTRAINT PK_JUKEBOX_LIKES PRIMARY KEY (jlid)
);
CREATE TABLE chat_messages (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    room_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    content VARCHAR2(1000 BYTE),
    created_at TIMESTAMP DEFAULT systimestamp,
    CONSTRAINT PK_CHAT_MESSAGES PRIMARY KEY (id)
);
CREATE TABLE songs (
    sid NUMBER GENERATED ALWAYS AS IDENTITY,
    mid NUMBER NOT NULL,
    title VARCHAR2(50 CHAR) NOT NULL,
    artist VARCHAR2(50 CHAR) NOT NULL,
    video_id VARCHAR2(255 BYTE) NOT NULL,
    duration NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT PK_SONGS PRIMARY KEY (sid)
);
CREATE TABLE profiles (
    pid NUMBER GENERATED ALWAYS AS IDENTITY,
    mid NUMBER NOT NULL,
    nickname VARCHAR2(50 CHAR) NOT NULL,
    birthdate DATE,
    img_name VARCHAR2(255 CHAR),
    img_url VARCHAR2(512 CHAR),
    main_address VARCHAR2(255 CHAR),
    status_message VARCHAR2(255 CHAR),
    intro CLOB,
    jid NUMBER,
    CONSTRAINT PK_PROFILES PRIMARY KEY (pid)
);
CREATE TABLE chat_rooms (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    is_group CHAR(1 BYTE) DEFAULT 'N',
    status VARCHAR2(20 BYTE) DEFAULT 'ACTIVE',
    created_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT systimestamp,
    CONSTRAINT PK_CHAT_ROOMS PRIMARY KEY (id)
);
CREATE TABLE diarys (
    did NUMBER GENERATED ALWAYS AS IDENTITY,
    mid NUMBER NOT NULL,
    title VARCHAR2(80 CHAR) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    updated_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    emo VARCHAR2(10 BYTE) NOT NULL,
    weather VARCHAR2(10 BYTE),
    CONSTRAINT PK_DIARYS PRIMARY KEY (did)
);
CREATE TABLE tracks (
    trid NUMBER GENERATED ALWAYS AS IDENTITY,
    jid NUMBER NOT NULL,
    sid NUMBER NOT NULL,
    CONSTRAINT PK_TRACKS PRIMARY KEY (trid)
);
CREATE TABLE jukeboxes (
    jid NUMBER GENERATED ALWAYS AS IDENTITY,
    mid NUMBER NOT NULL,
    title VARCHAR2(100 CHAR) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    updated_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT PK_JUKEBOXES PRIMARY KEY (jid)
);
CREATE TABLE friends (
    fid NUMBER GENERATED ALWAYS AS IDENTITY,
    req_id NUMBER NOT NULL,
    acc_id NUMBER NOT NULL,
    status VARCHAR2(10 BYTE) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    updated_at TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT PK_FRIENDS PRIMARY KEY (fid)
);
