spring.application.name=myWorld-back

# ## 서버 포트
server.port=8080

## 터미널 칼라 출력
spring.output.ansi.enabled=ALWAYS

## 로깅
# xxx
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

## 파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# 데이터베이스
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${DB_USERNAME:myworld}
spring.datasource.password=${DB_PASSWORD:myworld}
spring.jmx.enabled=false

## MyBatis
mybatis.config-location=classpath:mybatis/mapper-config.xml
mybatis.mapper-locations=classpath:mybatis/*/*.xml

# secrets.properties import
spring.config.import=optional:classpath:application-secrets.properties

# ${user.home}은 프로그램을 실행하는 사용자의 홈 디렉터리를 자동으로 찾아줍니다.
# 윈도우: C:/Users/KOSA
# 리눅스: /home/ubuntu
file.upload-dir=${FILE_UPLOAD_DIR:${user.home}/uploads}

# 프론트 배포 주소와 백엔드 공개 주소
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost,http://localhost:80,http://127.0.0.1:80}
app.public-base-url=${APP_PUBLIC_BASE_URL:http://localhost:8080}
